---
title:  Title Page
author: 
date: \today
fontsize: 12pt
margin: 2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
spacing: onehalf
papersize: a4paper
output:
  pdf_document:
    number_sections: no
    keep_tex: no
    toc: no
    template: title-page-template.latex
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# If you need to install any package while knitting the document
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos = r)
```

### Manuscript Title

\noindent "Paper Title"

### Authors

\noindent Danilo Freire: Senior Lecturer, School of Social and Political Sciences, University
of Lincoln, Brayford Pool, Lincoln, Lincolnshire LN6 7TS, United Kingdom,
<dfreire@lincoln.ac.uk>, <https://danilofreire.github.com>. Corresponding
author.

\vspace{.4cm}

\noindent Umberto Mignozzetti: Assistant Teaching Professor, Department of
Political Science and Computational Social Science Program, University of
California, San Diego, SSB 393, 2997 Thurgood Marshall Ln, La Jolla, CA 92037,
United States of America, <umbertomig@ucsd.edu>, <https://umbertomig.com>.

### Data Availability Statement

Replication materials are available at <https://github.com/danilofreire>.

### Funding Statement

This research was funded by the Fundação Getulio Vargas Applied Research Grant
Office (RPCAP-FGV). The funding body did not interfere in the study design or
implementation.

### Conflict of Interest Disclosure

The authors declare that no competing interests exist, financial or otherwise.

### Ethics Approval Statement

The experiment was pre-registered using the EGAP pre-registry tool (20180504AA)
and received IRB approval from New York University (IRB-FY2017-17) and Fundação
Getulio Vargas (IRB-01/2017).

